### ISSUE TITLE
Can I use it in VS2012 directly?

### ISSUE THREAD

**Issue by shonehang** [mingyuliutw/FastDirectionalChamferMatching#1]
Now I can use it in matlab by mexw64, but I want to use it in vs2012.
How do I modify this code?
Thanks very much!

**Comment by mingyuliutw** [comment]
To compile it with Microsoft VS 2012, you need to install VS 2012 and setup the library path correctly and replace obsolete function calls in the source code if there is any. It should be straightforward once you gain experiences with VS 2012. However, I would not be able to help you with the issue because I do not use VS anymore.

**Comment by shonehang** [comment]
Thanks!
